#!/usr/bin/env bash
# Re-vendor the whisper.cpp + ggml (CPU backend) sources this plugin compiles.
#
#   scripts/vendor_whisper.sh [tag]      # default: the pinned tag below
#
# Copies only what the cpp_archive build in priv/mob_plugin.exs needs (the
# whisper model code, ggml core, the ggml CPU backend with its ARM and x86
# kernels: arm64/armv7 phones and the x86_64 emulator) into c_src/whisper.cpp/,
# plus whisper.cpp's LICENSE and a VERSION stamp. GPU backends, other CPU
# architectures, examples and models are left out.
# After bumping the tag: update the source list in priv/mob_plugin.exs if
# upstream added or renamed files, and the version in README/CHANGELOG.
set -euo pipefail

TAG="${1:-v1.9.4}"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DEST="$ROOT/c_src/whisper.cpp"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

git -c advice.detachedHead=false clone --quiet --depth 1 --branch "$TAG" https://github.com/ggml-org/whisper.cpp "$TMP/w"
SRC="$TMP/w"

rm -rf "$DEST"
mkdir -p "$DEST/include" "$DEST/src" "$DEST/ggml/include" "$DEST/ggml/src/ggml-cpu/arch"

cp "$SRC/LICENSE" "$DEST/LICENSE"
cp "$SRC/include/whisper.h" "$DEST/include/"
cp "$SRC/src/whisper.cpp" "$SRC/src/whisper-arch.h" "$DEST/src/"

cp "$SRC"/ggml/include/{ggml.h,ggml-alloc.h,ggml-backend.h,ggml-cpp.h,ggml-cpu.h,ggml-opt.h,gguf.h} \
  "$DEST/ggml/include/"

# ggml core: the sources upstream's CMake compiles into ggml-base. That includes
# ggml-backend-dl.cpp even in this CPU-only build: ggml-backend-reg.cpp calls
# its dl_* helpers unconditionally (ggml_backend_load*), so without it the
# archive only links when the final link dead-strips (MOB-470).
for f in ggml.c ggml.cpp ggml-alloc.c ggml-backend.cpp ggml-backend-dl.cpp ggml-backend-meta.cpp \
  ggml-backend-reg.cpp ggml-opt.cpp ggml-quants.c ggml-threading.cpp gguf.cpp \
  ggml-backend-impl.h ggml-backend-dl.h ggml-common.h ggml-impl.h ggml-quants.h ggml-threading.h \
  ggml-feats.h; do
  cp "$SRC/ggml/src/$f" "$DEST/ggml/src/"
done

# ggml-version.h is generated by CMake from ggml-version.h.in.
sed -e 's/@GGML_VERSION_MAJOR@/0/; s/@GGML_VERSION_MINOR@/0/; s/@GGML_VERSION_PATCH@/0/' \
  -e "s/@GGML_VERSION@/whisper.cpp-$TAG/; s/@GGML_BUILD_COMMIT@/$TAG/" \
  "$SRC/ggml/src/ggml-version.h.in" > "$DEST/ggml/src/ggml-version.h"

# ggml CPU backend: every top-level source/header, the ARM kernels, and the
# headers ggml-cpu.cpp includes unconditionally (amx/*.h compile to nothing
# off x86) or under an option we leave off (llamafile/sgemm.h).
find "$SRC/ggml/src/ggml-cpu" -maxdepth 1 -type f \( -name '*.c' -o -name '*.cpp' -o -name '*.h' \) \
  -exec cp {} "$DEST/ggml/src/ggml-cpu/" \;
cp -R "$SRC/ggml/src/ggml-cpu/arch/arm" "$SRC/ggml/src/ggml-cpu/arch/x86" "$DEST/ggml/src/ggml-cpu/arch/"
mkdir -p "$DEST/ggml/src/ggml-cpu/llamafile" "$DEST/ggml/src/ggml-cpu/amx"
cp "$SRC/ggml/src/ggml-cpu/llamafile/sgemm.h" "$DEST/ggml/src/ggml-cpu/llamafile/"
cp "$SRC"/ggml/src/ggml-cpu/amx/*.h "$DEST/ggml/src/ggml-cpu/amx/"

echo "$TAG $(git -C "$SRC" rev-parse HEAD)" > "$DEST/VERSION"
echo "vendored whisper.cpp $TAG into $DEST"
